# Generated by Django 6.0.4 on 2026-05-02 11:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('patient_number', models.AutoField(primary_key=True, serialize=False, verbose_name='رقم المريض')),
                ('name', models.CharField(max_length=150, verbose_name='الاسم')),
                ('gender', models.CharField(choices=[('M', 'ذكر'), ('F', 'أنثى')], max_length=1, verbose_name='الجنس')),
                ('birth_date', models.DateField(verbose_name='تاريخ الميلاد')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='رقم الهاتف')),
                ('address', models.TextField(blank=True, verbose_name='العنوان')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'مريض',
                'verbose_name_plural': 'المرضى',
            },
        ),
        migrations.CreateModel(
            name='Specialty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='التخصص')),
            ],
            options={
                'verbose_name': 'تخصص',
                'verbose_name_plural': 'التخصصات',
            },
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='رقم الهاتف')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
                ('specialty', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='clinic.specialty', verbose_name='التخصص')),
            ],
            options={
                'verbose_name': 'دكتور',
                'verbose_name_plural': 'الأطباء',
            },
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appointment_date', models.DateField(verbose_name='تاريخ الموعد')),
                ('appointment_time', models.TimeField(verbose_name='وقت الموعد')),
                ('status', models.CharField(choices=[('pending', 'قيد الانتظار'), ('confirmed', 'مؤكد'), ('completed', 'مكتمل'), ('cancelled', 'ملغي')], default='pending', max_length=20, verbose_name='الحالة')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='clinic.doctor', verbose_name='الدكتور')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='clinic.patient', verbose_name='المريض')),
                ('specialty', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='clinic.specialty', verbose_name='التخصص')),
            ],
            options={
                'verbose_name': 'موعد',
                'verbose_name_plural': 'المواعيد',
                'ordering': ['appointment_date', 'appointment_time'],
            },
        ),
        migrations.CreateModel(
            name='MedicalRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visit_date', models.DateField(verbose_name='تاريخ الزيارة')),
                ('diagnosis', models.TextField(verbose_name='التشخيص')),
                ('symptoms', models.TextField(blank=True, verbose_name='الأعراض')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات الطبيب')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('appointment', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='medical_record', to='clinic.appointment', verbose_name='الموعد')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinic.doctor', verbose_name='الدكتور')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medical_records', to='clinic.patient', verbose_name='المريض')),
            ],
            options={
                'verbose_name': 'سجل طبي',
                'verbose_name_plural': 'السجلات الطبية',
                'ordering': ['-visit_date'],
            },
        ),
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medication_name', models.CharField(max_length=200, verbose_name='اسم الدواء')),
                ('dosage', models.CharField(max_length=100, verbose_name='الجرعة')),
                ('frequency', models.CharField(max_length=100, verbose_name='التكرار')),
                ('duration', models.CharField(max_length=100, verbose_name='المدة')),
                ('instructions', models.TextField(blank=True, verbose_name='تعليمات إضافية')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinic.doctor', verbose_name='الدكتور')),
                ('medical_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prescriptions', to='clinic.medicalrecord', verbose_name='السجل الطبي')),
            ],
            options={
                'verbose_name': 'روشتة',
                'verbose_name_plural': 'الروشتات',
            },
        ),
    ]
