# Generated by Django 5.1.2 on 2026-05-02 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='consultation_fee',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8, verbose_name='سعر الكشف'),
        ),
        migrations.AddField(
            model_name='patient',
            name='national_id',
            field=models.CharField(blank=True, max_length=14, null=True, unique=True, verbose_name='الرقم القومي'),
        ),
    ]
