# Generated by Django 5.1.2 on 2026-05-03 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0002_appointment_consultation_fee_patient_national_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='prescription',
            options={'verbose_name': 'خطة جلسات', 'verbose_name_plural': 'خطط الجلسات'},
        ),
        migrations.RemoveField(
            model_name='prescription',
            name='dosage',
        ),
        migrations.RemoveField(
            model_name='prescription',
            name='duration',
        ),
        migrations.RemoveField(
            model_name='prescription',
            name='frequency',
        ),
        migrations.RemoveField(
            model_name='prescription',
            name='medication_name',
        ),
        migrations.AddField(
            model_name='prescription',
            name='completed_sessions',
            field=models.PositiveIntegerField(default=0, verbose_name='عدد الجلسات المنفذة'),
        ),
        migrations.AddField(
            model_name='prescription',
            name='first_session_date',
            field=models.DateField(blank=True, null=True, verbose_name='تاريخ أول جلسة'),
        ),
        migrations.AddField(
            model_name='prescription',
            name='injury_type',
            field=models.CharField(default=1, max_length=200, verbose_name='نوع الإصابة'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='prescription',
            name='last_session_date',
            field=models.DateField(blank=True, null=True, verbose_name='تاريخ آخر جلسة'),
        ),
        migrations.AddField(
            model_name='prescription',
            name='total_sessions',
            field=models.PositiveIntegerField(default=1, verbose_name='إجمالي عدد الجلسات'),
        ),
    ]
