# Generated by Django 5.1.2 on 2026-05-03 18:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0003_alter_prescription_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TherapySession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_date', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ ووقت الجلسة')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات الجلسة وتطور الحالة')),
                ('doctor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='clinic.doctor', verbose_name='الطبيب المعالج')),
                ('prescription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='clinic.prescription', verbose_name='خطة الجلسات')),
            ],
            options={
                'verbose_name': 'جلسة علاجية',
                'verbose_name_plural': 'الجلسات العلاجية',
                'ordering': ['-session_date'],
            },
        ),
    ]
