# Generated by Django 5.1.2 on 2026-05-04 23:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0004_therapysession'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='doctor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointments', to='clinic.doctor', verbose_name='الدكتور'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='specialty',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='clinic.specialty', verbose_name='التخصص'),
            preserve_default=False,
        ),
    ]
