# Generated by Django 5.1.2 on 2026-05-05 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0005_alter_appointment_doctor_alter_appointment_specialty'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='appointment_type',
            field=models.CharField(choices=[('new', 'كشف جديد'), ('followup', 'استشارة / متابعة'), ('session', 'جلسة علاجية')], default='new', max_length=20, verbose_name='نوع الموعد'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='consultation_fee',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8, verbose_name='السعر المدفوع'),
        ),
    ]
